"""Search (SEO) and AI-answer (GEO) metadata for www.mundyball.com.

Safe to re-run after any page edit (e.g. from a design chat): it replaces its own
block between the SEO markers, so nothing gets duplicated.

  python seo.py

What it does to every page in docs/:
  - title, meta description, canonical URL, robots
  - Open Graph + Twitter card (shared 1200x630 preview image)
  - JSON-LD structured data: the organization + website on every page, plus
    breadcrumbs, the tryout Event + FAQPage, and coach Person entries where relevant
  - swaps the inline base64 header/footer logos for the identical cached files in assets/
It also writes docs/sitemap.xml.
"""
import base64
import hashlib
import html
import json
import os
import re
import datetime

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docs")
SITE = "https://www.mundyball.com"
NAME = "Mundelein Jr. Mustangs Feeder Basketball"
OG_IMAGE = SITE + "/assets/og-image.png"
LOGO = SITE + "/assets/logo-m-primary.png"
EMAIL = "mundeleinboysbasketball@gmail.com"
PHONE = "+1-224-425-9490"
SAME_AS = [
    "https://instagram.com/MundyBall",
    "https://x.com/mundyball",
    "https://www.facebook.com/profile.php?id=61589366369605",
]
MHS = {
    "@type": "HighSchool",
    "name": "Mundelein High School",
    "address": {
        "@type": "PostalAddress",
        "streetAddress": "1350 W Hawley St",
        "addressLocality": "Mundelein",
        "addressRegion": "IL",
        "postalCode": "60060",
        "addressCountry": "US",
    },
}

PAGES = {
    "index.html": dict(
        path="/", crumb=None, type="WebPage",
        title="Mundelein Jr. Mustangs | Youth Feeder Basketball, Grades 4–8",
        desc="The official feeder basketball program for Mundelein High School. Boys and girls travel teams for grades 4–8, coached by MHS staff in Mundelein, IL.",
    ),
    "about.html": dict(
        path="/about", crumb="About", type="AboutPage",
        title="About the Jr. Mustangs | Mundelein High School Feeder Program",
        desc="Why the Mundelein Jr. Mustangs exist: fundamentals first, town over travel, and real court time for every player, all built to prepare kids for MHS basketball.",
    ),
    "tryouts.html": dict(
        path="/tryouts", crumb="Tryouts", type="WebPage",
        title="Jr. Mustangs Tryouts Nov 14, 15 & 21 (Tentative) | Mundelein Basketball",
        desc="Register free for Mundelein Jr. Mustangs basketball tryouts, tentatively November 14, 15 and 21, 2026, at Mundelein High School. Boys and girls, grades 4–8. No fee to try out.",
    ),
    "camps.html": dict(
        path="/camps", crumb="Camps", type="WebPage",
        title="Youth Basketball Camps in Mundelein, IL | Jr. Mustangs",
        desc="Basketball camps for boys and girls ages 8–14, run by Mundelein High School coaches with a 1:6 coach-to-camper ratio. Clinics and break camps coming soon.",
    ),
    "coaches.html": dict(
        path="/coaches", crumb="Coaches", type="WebPage",
        title="Coaches | Mundelein Jr. Mustangs Feeder Basketball",
        desc="Meet the Jr. Mustangs staff, led by Program Director Gio Paganis and MHS varsity head coaches Joe Scheuers and Sarah Teipel. Coaching jobs available.",
    ),
    "codes.html": dict(
        path="/codes", crumb="Code of Conduct", type="WebPage",
        title="Code of Conduct | Mundelein Jr. Mustangs Basketball",
        desc="The standards Jr. Mustangs players, parents, coaches, and volunteers agree to: training-first development, respect for the game, and clear communication.",
    ),
    "contact.html": dict(
        path="/contact", crumb="Contact", type="ContactPage",
        title="Contact | Mundelein Jr. Mustangs Feeder Basketball",
        desc="Questions about tryouts, camps, or coaching? Email mundeleinboysbasketball@gmail.com or call (224) 425-9490. Coach Paganis replies within 24 hours.",
    ),
}

START, END = "<!-- SEO:start (generated by seo.py) -->", "<!-- SEO:end -->"


def org():
    return {
        "@type": "SportsOrganization",
        "@id": SITE + "/#org",
        "name": NAME,
        "alternateName": ["Mundelein Jr. Mustangs", "Jr. Mustangs Feeder Basketball", "MundyBall"],
        "description": "The official feeder basketball program for Mundelein High School in Mundelein, Illinois. "
                       "Boys and girls travel teams for grades 4–8, coached by MHS staff, with a curriculum that mirrors the MHS varsity system.",
        "sport": "Basketball",
        "url": SITE + "/",
        "logo": LOGO,
        "image": OG_IMAGE,
        "email": EMAIL,
        "telephone": PHONE,
        "address": MHS["address"],
        "location": MHS,
        "areaServed": {"@type": "City", "name": "Mundelein, Illinois"},
        "sameAs": SAME_AS,
        "founder": {"@id": SITE + "/#gio-paganis"},
        "contactPoint": {
            "@type": "ContactPoint", "contactType": "customer support",
            "email": EMAIL, "telephone": PHONE, "areaServed": "US", "availableLanguage": "English",
        },
    }


def website():
    return {"@type": "WebSite", "@id": SITE + "/#website", "url": SITE + "/", "name": NAME,
            "alternateName": "MundyBall", "publisher": {"@id": SITE + "/#org"}, "inLanguage": "en-US"}


def text(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s))).strip()


def faq(src):
    items = []
    for q, a in re.findall(r'<details class="faq"[^>]*>\s*<summary[^>]*>(.*?)</summary>\s*<p[^>]*>(.*?)</p>', src, re.S):
        items.append({"@type": "Question", "name": text(q),
                      "acceptedAnswer": {"@type": "Answer", "text": text(a)}})
    return {"@type": "FAQPage", "@id": SITE + "/tryouts#faq", "mainEntity": items} if items else None


TRYOUT_DATES = ["2026-11-14", "2026-11-15", "2026-11-21"]  # update each season


def tryout_events():
    """One Event per tryout day, so search engines don't read it as a continuous week."""
    events = []
    for i, day in enumerate(TRYOUT_DATES, 1):
        events.append({
            "@type": "Event",
            "@id": SITE + "/tryouts#tryout-day-%d" % i,
            "name": "Mundelein Jr. Mustangs Basketball Tryouts, Day %d of %d" % (i, len(TRYOUT_DATES)),
            "description": "Tryouts for the 2026–27 Jr. Mustangs winter travel season (dates tentative until confirmed). Boys and girls in grades 4–8. "
                           "60-minute evaluation by the coaching staff; each player's time is emailed after registration.",
            "startDate": day,
            "endDate": day,
            "eventStatus": "https://schema.org/EventScheduled",
            "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
            "location": {"@type": "Place", "name": "Mundelein High School", "address": MHS["address"]},
            "image": OG_IMAGE,
            "organizer": {"@id": SITE + "/#org"},
            "isAccessibleForFree": True,
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD",
                       "availability": "https://schema.org/InStock", "url": SITE + "/tryouts#register"},
        })
    return events


def coaches():
    return [
        {"@type": "Person", "@id": SITE + "/#gio-paganis", "name": "Gio Paganis",
         "jobTitle": "Program Director and Head Coach, Mundelein Jr. Mustangs; Assistant Varsity Basketball Coach, Mundelein High School",
         "worksFor": {"@id": SITE + "/#org"},
         "alumniOf": {"@type": "CollegeOrUniversity", "name": "Purdue University"},
         "url": SITE + "/coaches"},
        {"@type": "Person", "name": "Joe Scheuers",
         "jobTitle": "Head Varsity Boys Basketball Coach, Mundelein High School",
         "alumniOf": {"@type": "CollegeOrUniversity", "name": "Trine University"},
         "url": SITE + "/coaches"},
        {"@type": "Person", "name": "Sarah Teipel",
         "jobTitle": "Head Girls Varsity Basketball Coach, Mundelein High School",
         "alumniOf": [{"@type": "CollegeOrUniversity", "name": "Western Illinois University"},
                      {"@type": "HighSchool", "name": "Mundelein High School"}],
         "url": SITE + "/coaches"},
    ]


def block(fname, meta, src):
    url = SITE + meta["path"]
    page = {"@type": meta["type"], "@id": url + "#webpage", "url": url, "name": meta["title"],
            "description": meta["desc"], "isPartOf": {"@id": SITE + "/#website"},
            "about": {"@id": SITE + "/#org"}, "inLanguage": "en-US"}
    graph = [org(), website(), page]
    if meta["crumb"]:
        crumbs = {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": meta["crumb"], "item": url}]}
        graph.append(crumbs)
        page["breadcrumb"] = {"@type": "BreadcrumbList", "itemListElement": crumbs["itemListElement"]}
    if fname == "tryouts.html":
        graph.extend(tryout_events())
        f = faq(src)
        if f:
            graph.append(f)
    if fname == "coaches.html":
        graph.extend(coaches())
    e = html.escape
    lines = [
        START,
        '<meta name="description" content="%s">' % e(meta["desc"]),
        '<link rel="canonical" href="%s">' % url,
        '<meta name="robots" content="index, follow, max-image-preview:large">',
        '<meta name="theme-color" content="#CC2027">',
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="%s">' % NAME,
        '<meta property="og:locale" content="en_US">',
        '<meta property="og:url" content="%s">' % url,
        '<meta property="og:title" content="%s">' % e(meta["title"]),
        '<meta property="og:description" content="%s">' % e(meta["desc"]),
        '<meta property="og:image" content="%s">' % OG_IMAGE,
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:alt" content="Mundelein Jr. Mustangs M logo">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:site" content="@mundyball">',
        '<meta name="twitter:title" content="%s">' % e(meta["title"]),
        '<meta name="twitter:description" content="%s">' % e(meta["desc"]),
        '<meta name="twitter:image" content="%s">' % OG_IMAGE,
        '<script type="application/ld+json">%s</script>' % json.dumps(
            {"@context": "https://schema.org", "@graph": graph}, ensure_ascii=False, indent=1).replace("</", "<\\/"),
        END,
    ]
    return "\n".join(lines)


def inline_images_to_files(src):
    """Replace base64 data URIs that are byte-identical to a file in assets/ with that file's URL."""
    by_hash = {}
    adir = os.path.join(ROOT, "assets")
    for n in os.listdir(adir):
        p = os.path.join(adir, n)
        if os.path.isfile(p):
            by_hash[hashlib.md5(open(p, "rb").read()).hexdigest()] = "/assets/" + n

    def swap(m):
        h = hashlib.md5(base64.b64decode(m.group(2))).hexdigest()
        return by_hash.get(h, m.group(0))
    return re.sub(r"data:image/(png|jpe?g|webp|gif);base64,([A-Za-z0-9+/=]+)", swap, src)


def process(fname, meta):
    p = os.path.join(ROOT, fname)
    src = open(p, encoding="utf-8").read()
    src = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", src, flags=re.S)
    # drop the old per-page tags this block now owns
    for pat in [r'<meta name="description"[^>]*>\s*', r'<link rel="canonical"[^>]*>\s*',
                r'<meta property="og:[^"]+"[^>]*>\s*', r'<meta name="twitter:[^"]+"[^>]*>\s*',
                r'<meta name="robots"[^>]*>\s*', r'<meta name="theme-color"[^>]*>\s*']:
        src = re.sub(pat, "", src)
    src = re.sub(r"<title>.*?</title>", "<title>%s</title>" % html.escape(meta["title"], quote=False), src, count=1, flags=re.S)
    src = src.replace("</title>", "</title>\n" + block(fname, meta, src), 1)
    src = inline_images_to_files(src)
    open(p, "w", encoding="utf-8", newline="").write(src)
    return len(src)


def sitemap():
    today = datetime.date.today().isoformat()
    rows = []
    for fname, meta in PAGES.items():
        pri = "1.0" if meta["path"] == "/" else ("0.9" if fname in ("tryouts.html", "camps.html") else "0.7")
        rows.append("  <url><loc>%s%s</loc><lastmod>%s</lastmod><priority>%s</priority></url>" % (SITE, meta["path"], today, pri))
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % "\n".join(rows)
    open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8", newline="\n").write(xml)


if __name__ == "__main__":
    for fname, meta in PAGES.items():
        before = os.path.getsize(os.path.join(ROOT, fname))
        after = process(fname, meta)
        print("%-14s %4d KB -> %4d KB" % (fname, before // 1024, after // 1024))
    sitemap()
    print("sitemap.xml written")
